apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "langfuse-controller-helm.fullname" . }}
  labels:
    {{- include "langfuse-controller-helm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - langfuse.io
  resources:
  - langfuseapikeys
  - langfusellmconnections
  - langfusemodels
  - langfuseprojects
  - langfuseprompts
  - langfusescoreconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - langfuse.io
  resources:
  - langfuseapikeys/finalizers
  - langfusellmconnections/finalizers
  - langfusemodels/finalizers
  - langfuseprojects/finalizers
  - langfuseprompts/finalizers
  - langfusescoreconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - langfuse.io
  resources:
  - langfuseapikeys/status
  - langfusellmconnections/status
  - langfusemodels/status
  - langfuseprojects/status
  - langfuseprompts/status
  - langfusescoreconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "langfuse-controller-helm.fullname" . }}
  labels:
    {{- include "langfuse-controller-helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "langfuse-controller-helm.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "langfuse-controller-helm.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
