{{- if and (not .Values.langfuse.existingSecret) .Values.langfuse.adminApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langfuse-controller-helm.fullname" . }}
  labels:
    {{- include "langfuse-controller-helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  LANGFUSE_ADMIN_API_KEY: {{ .Values.langfuse.adminApiKey | quote }}
{{- end }}
