{{- if and (not .Values.langfuse.existingSecret) (and .Values.langfuse.publicKey .Values.langfuse.secretKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langfuse-controller-helm.fullname" . }}
  labels:
    {{- include "langfuse-controller-helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  LANGFUSE_PUBLIC_KEY: {{ .Values.langfuse.publicKey | quote }}
  LANGFUSE_SECRET_KEY: {{ .Values.langfuse.secretKey | quote }}
{{- end }}
