---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - langfuse.io
  resources:
  - langfuseapikeys
  - langfusellmconnections
  - langfusemodels
  - langfuseprojects
  - langfuseprompts
  - langfusescoreconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - langfuse.io
  resources:
  - langfuseapikeys/finalizers
  - langfusellmconnections/finalizers
  - langfusemodels/finalizers
  - langfuseprojects/finalizers
  - langfuseprompts/finalizers
  - langfusescoreconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - langfuse.io
  resources:
  - langfuseapikeys/status
  - langfusellmconnections/status
  - langfusemodels/status
  - langfuseprojects/status
  - langfuseprompts/status
  - langfusescoreconfigs/status
  verbs:
  - get
  - patch
  - update
