apiVersion: langfuse.io/v1alpha1
kind: LangfuseLlmConnection
metadata:
  labels:
    app.kubernetes.io/name: langfuse-controller
    app.kubernetes.io/managed-by: kustomize
  name: langfusellmconnection-sample
spec:
  # TODO(user): Add fields here
