apiVersion: langfuse.io/v1alpha1
kind: LangfusePrompt
metadata:
  labels:
    app.kubernetes.io/name: langfuse-controller
    app.kubernetes.io/managed-by: kustomize
  name: langfuseprompt-sample
spec:
  # TODO(user): Add fields here
